const matches=[{date:'June 11, 2026',venue:'Mexico City',home:'Mexico',away:'South Africa',homeScore:2,awayScore:1,status:'Full Time',broadcaster:'Sports TV / Stream+'},{date:'June 12, 2026',venue:'Toronto',home:'Canada',away:'USA',homeScore:1,awayScore:1,status:'Live 78’',broadcaster:'Global Sports'},{date:'June 13, 2026',venue:'Los Angeles',home:'Brazil',away:'Japan',homeScore:3,awayScore:2,status:'Full Time',broadcaster:'Football Max'}];
const fixtures=[{date:'June 14, 2026',match:'Argentina vs Morocco',time:'8:30 PM IST',venue:'New York'},{date:'June 15, 2026',match:'France vs Korea Republic',time:'11:30 PM IST',venue:'Dallas'},{date:'June 16, 2026',match:'England vs Ghana',time:'12:30 AM IST',venue:'Miami'}];
const table=[['USA',2,1,1,0,2,4],['Canada',2,1,1,0,1,4],['Mexico',2,1,0,1,0,3],['South Africa',2,0,0,2,-3,0]];
const scorers=[['Lionel Messi','Argentina',3],['Kylian Mbappé','France',3],['Vinícius Jr','Brazil',2],['Harry Kane','England',2],['Christian Pulisic','USA',1],['Jonathan David','Canada',1]];
const broadcasters=[['India','Replace with official Indian broadcaster / OTT app'],['USA','Replace with official US broadcaster'],['UK','Replace with official UK broadcaster'],['Canada','Replace with official Canadian broadcaster'],['Brazil','Replace with official Brazilian broadcaster'],['Japan','Replace with official Japanese broadcaster']];
const $=id=>document.getElementById(id);
function renderCards(filter=''){const data=matches.filter(m=>JSON.stringify(m).toLowerCase().includes(filter.toLowerCase()));$('scoreCards').innerHTML=data.map(m=>`<article class="card"><div class="match-top"><span>${m.date}</span><span>${m.venue}</span></div><div class="teams"><div class="team"><span>${m.home}</span><span class="score">${m.homeScore}</span></div><div class="team"><span>${m.away}</span><span class="score">${m.awayScore}</span></div></div><p>Broadcaster: <b>${m.broadcaster}</b></p><span class="status">${m.status}</span></article>`).join('')||'<p>No match found.</p>'}
function renderFixtures(filter=''){const data=fixtures.filter(f=>JSON.stringify(f).toLowerCase().includes(filter.toLowerCase()));$('fixturesList').innerHTML=data.map(f=>`<div class="fixture"><div><b>${f.match}</b><br><small>${f.date} • ${f.venue}</small></div><strong>${f.time}</strong></div>`).join('')}
function renderTable(){$('pointsTable').innerHTML=table.map(t=>`<tr>${t.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}
function renderScorers(){$('scorers').innerHTML=scorers.map(s=>`<article class="small-card"><strong>${s[0]}</strong><p>${s[1]}</p><h3>${s[2]} Goals</h3></article>`).join('')}
function renderBroadcasters(filter=''){const data=broadcasters.filter(b=>b.join(' ').toLowerCase().includes(filter.toLowerCase()));$('broadcasters').innerHTML=data.map(b=>`<article class="broadcaster"><h3>${b[0]}</h3><p>${b[1]}</p></article>`).join('')}
$('searchInput').addEventListener('input',e=>{renderCards(e.target.value);renderFixtures(e.target.value);renderBroadcasters(e.target.value)});
function countdown(){const target=new Date('2026-06-12T20:30:00+05:30').getTime();const diff=target-Date.now();if(diff<=0){$('countdown').textContent='Match started';return}const h=Math.floor(diff/36e5),m=Math.floor(diff%36e5/6e4);$('countdown').textContent=`${h}h ${m}m`}
renderCards();renderFixtures();renderTable();renderScorers();renderBroadcasters();countdown();setInterval(countdown,60000);
